paths:
  /api/products/:
    get:
      summary: Get all products
      tags:
        - Products
      responses:
        "200":
          description: Successfully obtained all products
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          description: Could not obtain the products
        "500":
          description: Internal Server Error
    post:
      summary: Add a new product, only if you have an "admin" or "premium" role
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/body/AddProduct"
      responses:
        "200":
          description: A new product was successfully added
          content:
            application/json:
              schema:
                type: object
                example:
                  status: "success"
                  payload:
                    _id: ObjectId('fger6348ydeasd236487')
                    title: Musculosa blanca
                    description: Remera musculosa blanca
                    price: 6000
                    code: RMB
                    stock: 33
                    category: indumentaria
                    thumbnail: google.com
                    owner: "admin"
        "400":
          description: You do not have the necessary permissions to add products
        "500":
          description: Internal Server Error
  /api/products/{pid}:
    get:
      summary: Get a product by its id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: pid is the id of the product
          schema:
            $type: string
      responses:
        "200":
          description: The product was successfully obtained with the "pid" added
          content:
            application/json:
              schema:
                $ref: "#/components/getById/GetProductById"
        "400":
          description: Could not obtain the product with the "pid"
        "500":
          description: Internal server error
    put:
      summary: Modify a product by its product ID, if you are "admin" you can modify all, if you are "premium", only the products you created
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: pid is the id of the product
          schema:
            $type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/body/UpdateProduct"
      responses:
        "200":
          description: The product was successfully modified with the "pid"
          content:
            application/json:
              schema:
                $ref: "#/components/updateById/UpdateProductById"
        "400":
          description: Could not modify the product with the "pid"
        "500":
          description: Internal server error
    delete:
      summary: Delete a product by its id, if you are "admin" you can remove all, if you are "premium", only the products you created.
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: Pid is the id of the product
          schema:
            $type: string
      responses:
        "200":
          description: The product with the "pid" added was successfully deleted
        "400":
          description: Could not delete the product with the "pid"
        "500":
          description: Internal server error
components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: Autogenerated product id
        title:
          type: string
          description: Product name
        description:
          type: string
          description: Product description
        price:
          type: number
          description: Price of the product
        code:
          type: string
          description: Product code
        stock:
          type: number
          description: Product quantity
        category:
          type: string
          description: Product category
        thumbnail:
          type: string
          description: Product image
        owner:
          type: string
          description: Product creator
      example:
        - _id: ObjectId('fger6348ydeasd236487')
          title: Musculosa blanca
          description: Remera musculosa blanca
          price: 6000
          code: RMB
          stock: 33
          category: indumentaria
          thumbnail: google.com
          owner: "admin"
  getById:
    GetProductById:
      type: object
      properties:
        _id:
          type: string
          description: Autogenerated product id
        title:
          type: string
          description: Product name
        descripcion:
          type: string
          description: Product description
        price:
          type: number
          description: Price of the product
        code:
          type: string
          description: Product code
        stock:
          type: number
          description: Product quantity
        category:
          type: string
          description: Product category
        thumbnail:
          type: string
          description: Product image
        owner:
          type: string
          description: Product creator
      example:
        status : "success"
        payload:
          _id: ObjectId('fger6348ydeasd236487')
          title: Musculosa blanca
          description: Remera musculosa blanca
          price: 6000
          code: RMB
          stock: 33
          category: indumentaria
          thumbnail: google.com
          owner: "admin"
  updateById:
    UpdateProductById:
      type: object
      properties:
        _id:
          type: string
          description: Autogenerated product id
        title:
          type: string
          description: Product name
        descripcion:
          type: string
          description: Product description
        price:
          type: number
          description: Price of the product
        code:
          type: string
          description: Product code
        stock:
          type: number
          description: Product quantity
        category:
          type: string
          description: Product category
        thumbnail:
          type: string
          description: Product image
        owner:
          type: string
          description: Product creator
      example:
        status : "success"
        payload:
          _id: ObjectId('fger6348ydeasd236487')
          title: Musculosa blanca
          description: Remera musculosa blanca
          price: 6000
          code: RMB
          stock: 33
          category: indumentaria
          thumbnail: google.com
          owner: "admin"
  body:
    AddProduct:
      type: object
      properties:
        status:
          type: string
          description: Request status
        payload:
          type: object
          description: Product created
          properties:
            _id:
              type: string
              description: Autogenerated product id
            title:
              type: string
              description: Product name
            descripcion:
              type: string
              description: Product description
            price:
              type: number
              description: Price of the product
            code:
              type: string
              description: Product code
            stock:
              type: number
              description: Product quantity
            category:
              type: string
              description: Product category
            thumbnail:
              type: string
              description: Product description
            owner:
              type: string
              description: Product creator
      example:
        title: Musculosa blanca
        description: Remera musculosa blanca
        price: 6000
        code: RMB
        stock: 33
        category: indumentaria
        thumbnail: google.com
        owner: "admin"
    UpdateProduct:
      type: object
      properties:
        status:
          type: string
          description: Request status
        payload:
          type: object
          description: Product modified or error message
          properties:
            _id:
              type: string
              description: Autogenerated product id
            title:
              type: string
              description: Product name
            descripcion:
              type: string
              description: Product description
            price:
              type: number
              description: Price of the product
            code:
              type: string
              description: Product code
            stock:
              type: number
              description: Product quantity
            category:
              type: string
              description: Product quantity
            thumbnail:
              type: string
              description: Product image
            owner:
              type: string
              description: Product creator
      example:
        title: Musculosa blanca 2
        description: Remera musculosa blanca 2
        price: 5000
        code: RMB2
        stock: 55
        category: indumentaria
        thumbnail: google.com
        owner: "admin"